export const CURRENCY_OPTIONS = [
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "USD", label: "USD - US Dollar" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "KRW", label: "KRW - South Korean Won" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "TWD", label: "TWD - Taiwan Dollar" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "VND", label: "VND - Vietnamese Dong" },
  { value: "AED", label: "AED - UAE Dirham" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "ZAR", label: "ZAR - South African Rand" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "DKK", label: "DKK - Danish Krone" },
  { value: "PLN", label: "PLN - Polish Zloty" },
  { value: "CZK", label: "CZK - Czech Koruna" },
  { value: "HUF", label: "HUF - Hungarian Forint" },
  { value: "TRY", label: "TRY - Turkish Lira" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "PEN", label: "PEN - Peruvian Sol" },
  { value: "EGP", label: "EGP - Egyptian Pound" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "KES", label: "KES - Kenyan Shilling" },
  { value: "BDT", label: "BDT - Bangladeshi Taka" },
  { value: "PKR", label: "PKR - Pakistani Rupee" },
  { value: "LKR", label: "LKR - Sri Lankan Rupee" },
  { value: "MMK", label: "MMK - Myanmar Kyat" },
  { value: "KHR", label: "KHR - Cambodian Riel" },
  { value: "LAK", label: "LAK - Lao Kip" },
  { value: "BND", label: "BND - Brunei Dollar" },
  { value: "QAR", label: "QAR - Qatari Riyal" },
  { value: "KWD", label: "KWD - Kuwaiti Dinar" },
  { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "OMR", label: "OMR - Omani Rial" },
  { value: "JOD", label: "JOD - Jordanian Dinar" },
  { value: "ILS", label: "ILS - Israeli Shekel" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "UAH", label: "UAH - Ukrainian Hryvnia" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "BGN", label: "BGN - Bulgarian Lev" },
  { value: "HRK", label: "HRK - Croatian Kuna" },
  { value: "ISK", label: "ISK - Icelandic Krona" },
];

export const TIMEZONE_OPTIONS = [
  { value: "UTC", label: "UTC (GMT+0)" },
  { value: "+08:00", label: "GMT+8 (Singapore/Malaysia)" },
  { value: "+07:00", label: "GMT+7 (Bangkok/Jakarta)" },
  { value: "+09:00", label: "GMT+9 (Tokyo/Seoul)" },
  { value: "+05:30", label: "GMT+5:30 (India)" },
  { value: "+10:00", label: "GMT+10 (Sydney)" },
  { value: "+01:00", label: "GMT+1 (London BST/Paris)" },
  { value: "+02:00", label: "GMT+2 (Cairo/Johannesburg)" },
  { value: "+03:00", label: "GMT+3 (Moscow/Riyadh)" },
  { value: "+03:30", label: "GMT+3:30 (Tehran)" },
  { value: "+04:00", label: "GMT+4 (Dubai)" },
  { value: "+04:30", label: "GMT+4:30 (Kabul)" },
  { value: "+05:00", label: "GMT+5 (Karachi/Tashkent)" },
  { value: "+05:45", label: "GMT+5:45 (Kathmandu)" },
  { value: "+06:00", label: "GMT+6 (Dhaka/Almaty)" },
  { value: "+06:30", label: "GMT+6:30 (Yangon)" },
  { value: "+09:30", label: "GMT+9:30 (Adelaide)" },
  { value: "+11:00", label: "GMT+11 (Vladivostok)" },
  { value: "+12:00", label: "GMT+12 (Auckland)" },
  { value: "+13:00", label: "GMT+13 (Samoa)" },
  { value: "-01:00", label: "GMT-1 (Azores)" },
  { value: "-02:00", label: "GMT-2 (Mid-Atlantic)" },
  { value: "-03:00", label: "GMT-3 (São Paulo/Buenos Aires)" },
  { value: "-03:30", label: "GMT-3:30 (Newfoundland)" },
  { value: "-04:00", label: "GMT-4 (Atlantic)" },
  { value: "-05:00", label: "GMT-5 (New York/Toronto)" },
  { value: "-06:00", label: "GMT-6 (Chicago/Mexico City)" },
  { value: "-07:00", label: "GMT-7 (Denver)" },
  { value: "-08:00", label: "GMT-8 (Los Angeles)" },
  { value: "-09:00", label: "GMT-9 (Alaska)" },
  { value: "-10:00", label: "GMT-10 (Hawaii)" },
  { value: "-11:00", label: "GMT-11 (Midway)" },
];

export const COUNTRY_OPTIONS = [
  { value: "MY", label: "Malaysia" },
  { value: "SG", label: "Singapore" },
  { value: "US", label: "United States" },
  { value: "GB", label: "United Kingdom" },
  { value: "AU", label: "Australia" },
  { value: "NZ", label: "New Zealand" },
  { value: "CA", label: "Canada" },
  { value: "JP", label: "Japan" },
  { value: "KR", label: "South Korea" },
  { value: "CN", label: "China" },
  { value: "HK", label: "Hong Kong" },
  { value: "TW", label: "Taiwan" },
  { value: "TH", label: "Thailand" },
  { value: "ID", label: "Indonesia" },
  { value: "PH", label: "Philippines" },
  { value: "VN", label: "Vietnam" },
  { value: "IN", label: "India" },
  { value: "PK", label: "Pakistan" },
  { value: "BD", label: "Bangladesh" },
  { value: "LK", label: "Sri Lanka" },
  { value: "MM", label: "Myanmar" },
  { value: "KH", label: "Cambodia" },
  { value: "LA", label: "Laos" },
  { value: "BN", label: "Brunei" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "QA", label: "Qatar" },
  { value: "KW", label: "Kuwait" },
  { value: "BH", label: "Bahrain" },
  { value: "OM", label: "Oman" },
  { value: "JO", label: "Jordan" },
  { value: "IL", label: "Israel" },
  { value: "TR", label: "Turkey" },
  { value: "EG", label: "Egypt" },
  { value: "NG", label: "Nigeria" },
  { value: "KE", label: "Kenya" },
  { value: "ZA", label: "South Africa" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "IT", label: "Italy" },
  { value: "ES", label: "Spain" },
  { value: "PT", label: "Portugal" },
  { value: "NL", label: "Netherlands" },
  { value: "BE", label: "Belgium" },
  { value: "CH", label: "Switzerland" },
  { value: "AT", label: "Austria" },
  { value: "SE", label: "Sweden" },
  { value: "NO", label: "Norway" },
  { value: "DK", label: "Denmark" },
  { value: "FI", label: "Finland" },
  { value: "PL", label: "Poland" },
  { value: "CZ", label: "Czech Republic" },
  { value: "HU", label: "Hungary" },
  { value: "RO", label: "Romania" },
  { value: "BG", label: "Bulgaria" },
  { value: "HR", label: "Croatia" },
  { value: "GR", label: "Greece" },
  { value: "IE", label: "Ireland" },
  { value: "IS", label: "Iceland" },
  { value: "RU", label: "Russia" },
  { value: "UA", label: "Ukraine" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },
  { value: "AR", label: "Argentina" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colombia" },
  { value: "PE", label: "Peru" },
];
